# SPDX-FileCopyrightText: 1998 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

TOP=../..
include $(TOP)/configure/CONFIG

DB += table-csv.db
DB += table-sim.db
DB += table-soft.db
DB += table-soft-double.db
DB += table-stat.db
DB += table-cp.db

include $(TOP)/configure/RULES

